AllCops:
  TargetRubyVersion: 2.0

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

MultilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  ExcludedMethods: Struct.new
  Exclude:
    - spec/**/*.rb
